name: Test and Deployment
on:
  push:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
    env:
      STUDIOUSHEXAMEMORY_SERVER_PORT: 80
      STUDIOUSHEXAMEMORY_ENVIRONMENT: test
      STUDIOUSHEXAMEMORY_MONGODB_USER: root
      STUDIOUSHEXAMEMORY_MONGODB_PASSWORD: password
      STUDIOUSHEXAMEMORY_SESSION_SECRET: testing
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: MongoDB server start
        uses: supercharge/mongodb-github-action@1.3.0

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to demonstration server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEMO_HOST }}
          username: ${{ secrets.DEMO_USERNAME }}
          key: ${{ secrets.DEMO_KEY }}
          passphrase: ${{ secrets.DEMO_PASSPHRASE }}
          port: ${{ secrets.DEMO_PORT }}
          script: |
            cd ~/node-servers/studious-hexa-memory-demo
            git pull origin master
            sudo su
            sudo pm2 restart studious-hexa-memory-demo
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          passphrase: ${{ secrets.PROD_PASSPHRASE }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            sudo su
            cd ~/node-servers/studious-hexa-memory
            git pull origin master
            sudo su
            sudo pm2 restart studious-hexa-memory
