name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
    env:
      STUDIOUSHEXAMEMORY_SERVER_PORT: 8000
      STUDIOUSHEXAMEMORY_ENVIRONMENT: test
      STUDIOUSHEXAMEMORY_MONGODB_URI: mongodb://localhost:27017/
      STUDIOUSHEXAMEMORY_SESSION_SECRET: testing
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: MongoDB server start
        uses: supercharge/mongodb-github-action@1.3.0

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
